services:
  sender:
    container_name: sender
    build: ./
    environment:
      - REDIS_URL=redis://redis:6379
      - ADD=1

  listener:
    container_name: listener
    build: ./
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:6.2.5-alpine3.14
    container_name: redis
    ports:
      - 6379:6379

